sudo: false

language: go

go:
  - 1.7.4

before_install:
  - go get -v github.com/Masterminds/glide
  - go get -v github.com/mitchellh/gox
  - go get -v github.com/tcnksm/ghr

install:
  - glide install

script:
  - gox -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}" -arch="386 amd64 arm" -os="linux darwin windows freebsd openbsd"

after_success:
  - ./scripts/deploy
